app.coffee, package.json
add support for the /profile timing url
=> add v8 profiler

app.coffee, app/coffee/CompileController.coffee, app/coffee/CompileManager.coffee
Provide endpoints to list and delete files in the project
=> Datajoy show output files

app.coffee, app/coffee/OutputCacheManager.coffee
support url to pdf /project/project_id/build/build_id/output/*
make build_id a secure random token (8 random bytes from crypto.getRandomBytes)
=> Add fast path to pdf

app.coffee, app/coffee/CompileController.coffee, app/coffee/CompileManager.coffee, app/coffee/ProjectPersistenceManager.coffee, test/unit/coffee/CompileControllerTests.coffee, test/unit/coffee/CompileManagerTests.coffee, test/unit/coffee/ProjectPersistenceManagerTests.coffee
add per-user routes and methods
=> Per user containers part 2

app.coffee, app/coffee/CommandRunner.coffee, app/coffee/CompileController.coffee, app/coffee/CompileManager.coffee, app/coffee/LatexRunner.coffee
keep track of running jobs and allow them to be killed
=> add support for stopping compile

app/coffee/CommandRunner.coffee, app/coffee/CompileController.coffee, app/coffee/CompileManager.coffee, app/coffee/LatexRunner.coffee, app/coffee/RequestParser.coffee, test/unit/coffee/CompileManagerTests.coffee, test/unit/coffee/LatexRunnerTests.coffee
pass environment variables down to CommandRunner, so we can provide options to chktex
=> Add chktex support

app/coffee/CompileManager.coffee, test/unit/coffee/CompileManagerTests.coffee
the .tex files produced from knitr have macros which confuse chktex
=> only run chktex on .tex files, not .Rtex files

app/coffee/CompileManager.coffee, app/coffee/ResourceWriter.coffee, app/coffee/TikzManager.coffee, test/unit/coffee/ResourceWriterTests.coffee, test/unit/coffee/TikzManager.coffee
make copy of main file as output.tex when tikz/pgf are in use
=> support for tikz externalize

app/coffee/RequestParser.coffee, test/unit/coffee/RequestParserTests.coffee
check for root resource since TikzManager now uses it
=> additional check for valid rootResource

app/coffee/OutputFileOptimiser.coffee, test/unit/coffee/OutputFileOptimiserTests.coffee
when qpdf runs inside the container we want to avoid processing the file again outside
=> check if file is optimised before running qpdf

test/acceptance/coffee/ExampleDocumentTests.coffee
add acceptance tests to check that qpdf runs correctly inside the docker container
=> use pdfinfo on output to ensure pdfs are optimised

app/coffee/OutputCacheManager.coffee
setting to prevent any optimisation with qpdf outside docker
=> add setting to avoid optimisations outside docker

app/coffee/CompileManager.coffee, test/unit/coffee/CompileManagerTests.coffee
we are getting errors running synctex when the output file does not exist (or maybe has the wrong permissions)
=> check file exists before running synctex

app/coffee/TikzManager.coffee, test/unit/coffee/CompileManagerTests.coffee, test/unit/coffee/TikzManager.coffee
avoid exception in tikzmanager for empty files
=> fix tikzmanager exception

config/settings.defaults.coffee
Updates to newer docker-runner-sharelatex config
=> Update docker-runner-sharelatex config

Jenkinsfile, test/acceptance/coffee/ExampleDocumentTests.coffee, test/acceptance/scripts/settings.test.coffee
Add jenkins file to build CLSI on new builds server. Requires merge of https://github.com/sharelatex/docker-runner-sharelatex/pull/20 before this will run correctly on new CI.
=> Add jenkinsfile

test/acceptance/coffee/helpers/Client.coffee
avoid confusion if existing process is already listening on the port
connects to overleaf/sharelatex#227
=> exit if mock server fails to start

test/smoke/coffee/SmokeTests.coffee
Fixes a race condition where smoke tests exit before container can be attached to.
See here for more info: https://github.com/overleaf/sharelatex/issues/274
=> Add a 1 second delay to the smoke tests

.travis.yml
See https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions-using-.nvmrc
=> Make travis read the node version from the .nvmrc file

Dockerfile, app.coffee, app/coffee/RequestParser.coffee, npm-shrinkwrap.json, package.json, test/acceptance/coffee/ExampleDocumentTests.coffee
Minimum 
Contributes to: overleaf/sharelatex#1118
To be used in conjunction with https://github.com/sharelatex/sharelatex-dev-environment/pull/166
=> Upgrade to Node 10 - CLSI

npm-shrinkwrap.json, package.json
Bump logger to 1.6.0
N/A
Contributes to https://github.com/sharelatex/overleaf-google-ops/issues/204
Low
- [ x] Compiles still work on staging
@henryoswald
=> Bump logger to v1.6.0

Jenkinsfile, Makefile, buildscript.txt, docker-compose.ci.yml, docker-compose.yml, package.json, test/acceptance/coffee/ExampleDocumentTests.coffee
Proposed fix for https://github.com/sharelatex/sharelatex-dev-environment/issues/195
connects to https://github.com/sharelatex/sharelatex-dev-environment/issues/195
=> increase timeout for long-running acceptance tests

Makefile, buildscript.txt, docker-compose.ci.yml, docker-compose.yml
If set the TEXLIVE_IMAGE variable will be passed through.
Seems to be required for https://github.com/overleaf/google-ops/issues/308
Limited to build environment
N/A
N/A
N/A
N/A
@henryoswald
=> Pass through TEXLIVE_IMAGE

Dockerfile
Upgrade to node:10.19.0, built from source.  Will update to public node image when it becomes available.
=> update to gcr.io/overleaf-ops/node:10.19.0

app.js, app/js/DockerRunner.js, app/js/LatexRunner.js, app/js/UrlFetcher.js, config/settings.defaults.js, test/unit/js/LatexRunnerTests.js, test/unit/js/ResourceWriterTests.js, test/unit/js/UrlFetcherTests.js
Fixes lint and format checks
NA
NA
Fixes lint and format checks only.
CLSI so high, but changes are small.
NA
NA
NA
NA
NA
=> fix format and lint checks

app.js
Send a 503 Unavailable response when the docker container cannot be inspected.
NA
Original investigation of EPIPE errors https://github.com/overleaf/clsi/pull/162
Handling for this PR in web https://github.com/overleaf/web-internal/pull/2902
Issue https://github.com/overleaf/issues/issues/2913
Small change.
Low, changes a 500 error to a 503.
NA
NA
NA
In combination with https://github.com/overleaf/web-internal/pull/2902 should reduce the number of user visible 5xx errors on compiles during a deploy.
@henryoswald
=> send 503 unavailable response on EPIPE

README.md
This clarifies the exact way to construct this request. It seems that
some users have taken the existing documentation to mean that the
request should be sent from the browser, to the web server. This example
clarifies how to send this compile request directly to the clsi server.
- Fixes https://github.com/overleaf/issues/issues/3641
=> In example request, show example using curl

app/js/OutputFileFinder.js, test/unit/js/OutputFileFinderTests.js
Decaff cleanup of OutputFileManager
NA
NA
I have also replaced {} by a Set for safety.
Generating list of output files
NA
NA
NA
NA
=> decaff cleanup of OutputFileManager

app/js/ResourceStateManager.js
Reverts overleaf/clsi#200
This had an exception that showed up after a while:
```
/app/app/js/ResourceStateManager.js:65
const array = result.toString().split('\n')
^
TypeError: Cannot read property 'toString' of undefined
at /app/app/js/ResourceStateManager.js:65:28
at /app/app/js/SafeReader.js:29:16
at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```
=> Revert "decaff cleanup ResourceStateManager"

app.js
Also support post requests for getting project status. Once https://github.com/overleaf/web-internal/pull/3776 is merged we can remove the get request. although it currently doesn't work I would rather not create loads of 404's by removing it first.
https://github.com/overleaf/web-internal/pull/3776 
https://github.com/overleaf/issues/issues/3909
Low, this code doesn't currently really work so it can't get much worse!
=> support post and get for getting status of clsi project

app.js, app/js/ContentCacheManager.js, app/js/OutputCacheManager.js
Add express validation for the contentId and hash in line with other parameters.
NA
#226 
Adds validation only.
Content URLs only
NA
Deploy clsi
NA
NA
NA
=> add validation for express content routes

app/js/ProjectPersistenceManager.js
Logs the expiry timeout so we can monitor it while the new content caching rolls out.
NA
#226 
Logging change only
Expiry of projects
NA
Deploy with clsi
NA
NA
cc @das7pad
=> log the expiry timeout value when disk space is low

package-lock.json, package.json
Upgrade to latest `fs-extra` module
NA
#231 
Not needed for #231 but upgrading while I'm looking at this area.
Compile
NA
NA
NA
NA
NA
=> upgrade fs-extra

app/js/ContentCacheManager.js
This PR is making the writing of streams to disk _atomically_ using an intermediate file for writing and a final rename operation.
In case the writing or rename operation fails, unlink the file.
Low.
- clear output dir
- re-compile
- see cached assets
=> [ContentCacheManager] write streams to disk atomically

test/unit/js/ContentCacheManagerTests.js
Followup for #234 
Followup for #235 
This PR is fixing the unit tests, implementing the logic behind rename operations.
Followup for #234 
Followup for #235 
Low
- run unit tests locally
=> [misc] fix unit tests following the merge of atomic writes

app/js/LatexRunner.js, test/unit/js/LatexRunnerTests.js
There are some broken/empty timings related to `$ time -v ...` runs, that we can skip sending to prom/the frontend when missing.
<details>
Prom graph for one of them, showing all-zero scrapes.
</details>
Low.
- see added unit tests
=> [LatexRunner] do not emit empty cpu/sys timings

app/js/ProjectPersistenceManager.js, app/js/UrlCache.js
For https://github.com/overleaf/issues/issues/4454
This PR is adding a few timing collections to sqlite access.
For https://github.com/overleaf/issues/issues/4454
=> [misc] track delays of using sqlite in a few places

package.json
For https://console.cloud.google.com/cloud-build/builds;region=global/b0f7b90c-ebad-445f-b178-f27e419cd7fe;step=2?project=overleaf-ops
#221 
Low
- run lint locally
=> [misc] add missing dependency entry for send

app.js
Reverts overleaf/clsi#251
As discussed, we will deploy https://github.com/overleaf/clsi/pull/256 first.
=> Revert "very basic mvp for shedding load"

app/js/DockerRunner.js, config/settings.defaults.js
Add more docker options to the settings file.
NA
NA
Similar to the existing option for the seccomp profile.
Not used unless option is set.
NA
NA
NA
NA
cc @gh2k
=> add option for apparmor profile
