app.coffee
app/coffee/CompileController.coffee
test/unit/coffee/CompileControllerTests.coffee

Avoid warnings in the logs about calls to deprecated express functions
replace  res.send(code)  with res.sendStatus(code)
http://expressjs.com/4x/api.html#res.sendStatus
and res.send(code,body) with res.status(code).send(body)
http://expressjs.com/4x/api.html#res.status
http://expressjs.com/4x/api.html#res.send

replace deprecated express send(code,body) calls

---

app/coffee/UrlFetcher.coffee
test/unit/coffee/UrlFetcherTests.coffee

The main fix is to attach the error handlers before piping, not after, so we don't get uncaught errors leading to the callback never being called.
Other changes
- add a 1 minute timeout to the request.get call
- only create the writeStream if the urlStream is successful (avoids creating an empty file)
- unlink the output file if there's an error on the writeStream (avoid empty/half-written output file)
- pause the request stream until we have piped it to the writestream, avoids missing the early bytes
- set an overall 3 minute time limit on the whole function

clean up error handling in UrlFetcher

---

app/coffee/db.coffee

Add indexes to mysql tables, note - needs upgrade to sequelize in another pull request for these to actually be created (with earlier versions the indexes aren't created, but the code still runs ok).

add indexes to mysql db

---

app/coffee/CompileController.coffee
test/unit/coffee/CompileControllerTests.coffee

the url attribute will now give the preferred location for accessing the output file, without the url having to be constructed by the web client

Per user containers part 1

---

app/coffee/OutputCacheManager.coffee

We are caching multiple build directories even for a single user, we only need the new and existing builds to be cached.

Reduce number of cached builds for per-user containers

---

config/settings.defaults.coffee

`project_cache_length_ms` was only `60*60*24 = 1.5 min` which is a little bit short. Default of one day seams more reasonable.

Set default project_cache_length_ms to 1 day

---

app/coffee/LatexRunner.coffee

this avoids problems in the latest version of latexmk where the $pdflatex variable has been replaced by $xelatex and $lualatex when running with -xelatex or -lualatex

allow latexmk to pass through options

---

app/coffee/CompileController.coffee

just log compile timeouts instead of reporting them to sentry

don't report compile timeouts to sentry

---

app/coffee/ResourceWriter.coffee

avoid problem where user is compiling different main files and output.xdv is cached from the first one

delete intermediate xdv files from xelatex

---

app/coffee/LatexRunner.coffee

Log a warning instead and continue.

Killing an already stopped project is not an error

---

app.coffee
app/coffee/CompileManager.coffee
app/coffee/Errors.coffee

This is semantically nicer than the 500 response which used to be
produced in these circumstances.

Send a 404 if the project files have gone away when running synctex.

---

app/coffee/CompileController.coffee
app/coffee/CompileManager.coffee
app/coffee/DraftModeManager.coffee
app/coffee/Errors.coffee
app/coffee/RequestParser.coffee
app/coffee/ResourceListManager.coffee
app/coffee/ResourceStateManager.coffee
app/coffee/ResourceWriter.coffee
app/coffee/SafeReader.coffee
test/unit/coffee/CompileManagerTests.coffee
test/unit/coffee/RequestParserTests.coffee
test/unit/coffee/ResourceWriterTests.coffee

if request has an option incremental:<state-id> and the <state-id> matches the value from the last full compile, then write the content in the request incrementally into the compile directory.
if the request has an option state:<state-id> it is a full compile and the state id is written into the compile directory in the file .resource-state
if the state-id on an incremental compile doesn't match the value in the .resource-state file, return a response of 409 (Conflict).
Outstanding tasks:

Write files incrementally

---

app/coffee/OutputCacheManager.coffee
app/coffee/OutputFileFinder.coffee
app/coffee/ResourceStateManager.coffee
app/coffee/ResourceWriter.coffee
test/unit/coffee/ResourceStateManagerTests.coffee

OutputFileFinder ignores dot files, which causes a FilesOutOfSyncError for incremental compiles when there are dot files in the project.
This adds any extra check for any missing files, to confirm that they are actually not present in the directory (using fs.stat()) before giving an error.
Also added a check for relative paths, and unit tests for ResourceStateManager.

handle dot files in resource list

---

app/coffee/CompileController.coffee
app/coffee/CompileManager.coffee
app/coffee/Errors.coffee
app/coffee/LockManager.coffee
app/coffee/ResourceWriter.coffee
package.json
test/unit/coffee/CompileControllerTests.coffee
test/unit/coffee/CompileManagerTests.coffee
test/unit/coffee/LockManager.coffee

prevent two compiles from trying to run at the same time and clobbering the files in the compile directory.

lock compile directory

---

app/coffee/CompileManager.coffee
app/coffee/ResourceWriter.coffee
app/coffee/TikzManager.coffee
test/unit/coffee/CompileManagerTests.coffee
test/unit/coffee/TikzManager.coffee

1. keep tikz cached files
2. simplify tikzexternalize checks so they work with incremental compiles (always look at file on disk)
Now that we have full and incremental compiles to deal with, it's simpler if we just open the main file on disk every time and look at the content to see if tikzexternalize is used. 
I originally wrote this pull request to extend the existing check - i.e. look at the content in the incoming request first and then check the file on disk if the main file wasn't in the request, but that was overly complicated optimisation -- when we do the tex run itself it will open 10's or hundreds of files, so saving one file open in the node process isn't worth the complexity.

fix tikzexternalize ii

---

app/coffee/ResourceStateManager.coffee
app/coffee/SafeReader.coffee
app/coffee/TikzManager.coffee

we are logging end-of-file errors in the file reader, change it to let the caller decide when to do it
TikzManager is using it to look at the header of the file, it passes a small number of bytes to read -- when we read all of those it is triggering and end-of-file message in sentry.

fix read logging

---

app.coffee

The smoke tests can sometimes take ~20 seconds to complete, which causes the http POST to time out. This should solve that problem.

Increase smoke test interval to 30 seconds

---

app/coffee/CompileController.coffee

if the compilation produces a core file, log it as an error.

log an error if core file is found in output

---

config/settings.defaults.coffee
package.json

Makes this service compatible with https://github.com/sharelatex/sharelatex-dev-environment
Allows other service's locations to be passed in via environment variables which are provided by docker-compose. Also allows our docker-command-runner to be configured via environment variables.
Also provides an `npm run start` script as a common entry point to all services via docker-compose.

Provide hosts as settings and add npm run start script

---

app/coffee/CompileManager.coffee
test/unit/coffee/CompileManagerTests.coffee

Increase the timeout on wordcount to 1 minute as a legitimate project was hitting the 10 second timeout limit.
Fixes https://github.com/overleaf/sharelatex/issues/630

increase timeout on wordcount

---

app/coffee/ResourceWriter.coffee
test/unit/coffee/ResourceWriterTests.coffee

We are not caching files produced by epstopdf, which is slowing down compiles.  (I thought we used to do this!)
This excludes the generated files `...-eps-converted-to.pdf` from the `epstopdf` package.
Connects to https://github.com/overleaf/sharelatex/issues/877

cache pdf files generated by epstopdf

---

app/coffee/CompileManager.coffee
app/coffee/TikzManager.coffee
test/unit/coffee/TikzManager.coffee

Copy the main file to `output.tex` when using the `pstool` package because it only works when `filename === jobname`.
Connects to https://github.com/overleaf/sharelatex/issues/832

use TikzManager to create main file for pstool package

---

README.md

Define CLSI as "Common LaTeX Service Interface" on first use in README, as I always forget what it stands for.

Expand CLSI to Common LaTeX Service Interface on first use

---

app/coffee/CompileController.coffee
test/unit/coffee/CompileControllerTests.coffee

Same issue and fix as https://github.com/sharelatex/project-history-sharelatex/pull/267 but for clsi.  Affects synctex and wordcount.  I don't think these allow arbitrary output but fixing them anway. 
NA
Connects to https://github.com/overleaf/sharelatex/issues/1517
Same changes as before
NA
NA
NA
@jdleesmiller @jpallen

use explicit json content-type to avoid security issues with text/html

---

seccomp/clsi-profile.json

Last year golang changed from epoll_wait to epoll_pwait https://github.com/golang/go/issues/23750
This causes golang panic errors on mac when running secomp secure compiles using docker 18.09.1. It may start to become a problem on the clsi's where we are running on 17.03.2-ce in production.

add epoll_pwait to secomp profile

---

app/coffee/CompileManager.coffee
app/coffee/LatexRunner.coffee
app/coffee/RequestParser.coffee
test/unit/coffee/CompileManagerTests.coffee
test/unit/coffee/LatexRunnerTests.coffee
test/unit/coffee/RequestParserTests.coffee

Adds a `flags` parameter to the CLSI request JSON, appearing under the `compile.options` key (alongside such stalwarts as `compiler`, `timeout`, etc.).
This is primarily to support `-file-line-error` as an option, but could have other uses as well.
~~`flags` should be a string, or absent. If supplied, it is split on spaces and the resulting arguments are added to the base latexmk command.~~ `flags` should be an array of strings, or absent. If supplied, the listed arguments are added to the base latexmk command.
None.
https://github.com/overleaf/write_latex/pull/5201: CLSI-conversions require Overleaf's LaTeX log parser, which in turn expects logs built with `-file-line-error`. 
This is fairly straightforward. `RequestParser` captures the `flags` option if present, and stores it alongside …

Add flags option to request JSON

---

entrypoint.sh

The docker unix-group on the host running the docker container may have a different id than the group in the container. Changing the ownership/group of the docker socket may kill the access on the socket for non-root users on the docker host.
The group id varies per distribution and is easy to detect via stat call on the socket.
As the docker group may actually match in both environments we must add the new group gracefully via the `--non-unique` flag.

[docker] add support for a different docker group id on the docker host

---

app.coffee
app/coffee/RequestParser.coffee

In practice most projects will still be limited to five minutes,
but this allows us to bump up the limit for some projects,
especially legacy v1 projects that have been imported to v2
As far as I can tell, this is the last bottleneck in the call-stack where the timeout was being clamped to below ten minutes.
- Connects to https://github.com/overleaf/issues/issues/1308
- Allowing some projects to compile for longer, maybe increasing load on some instances?
@overleaf/support @henryoswald @jdleesmiller @mans0954

Increase the hard-timeout to 10 minutes.

---

app/coffee/CompileManager.coffee
app/coffee/LocalCommandRunner.coffee

I ran sharelatex/sharelatex:2.0-beta-2 using the [docker-compose.yml](https://github.com/overleaf/overleaf/blob/66c8f0a14ce01ddaa7c9123450d13ec1c3602b85/docker-compose.yml), just edited the image to `sharelatex/sharelatex:2.0-beta-2`.
I didn't use DOCKER_RUNNER and SANDBOXED_COMPILES.
I got 3 errors when I sync between TeX and PDF:
1. Undefined Settings.clsi.docker in CompileManager.js
2. Numbers were not converted to string in LocalCommandRunner.js
3. `stdout` was not sent to callback in LocalCommandRunner.js.
Further, `/opt/synctex` does not exist in the image `sharelatex/sharelatex:2.0-beta-2`, run `ln -s /var/www/sharelatex/clsi/bin/synctex /opt/synctex` could fix the issue.
This pull request fixes the errors, and then we can sync between TeX and PDF without DOCKER_RUNNER.
Error 1
``` …
```

Fix synctex for LocalCommandRunner

---

app/coffee/CompileController.coffee
app/coffee/CompileManager.coffee
app/coffee/DockerRunner.coffee
test/acceptance/coffee/TimeoutTests.coffee

The unconventional use of callbacks to return both an error and data
after compilation created a subtle bug where the output files were
dropped by the LockManager in case of an error such as a timeout.
This prevented the frontend to show error logs when a timeout occurs,
creating confusion among users.
We now attach the output files to the error so that they reach the
controller and are sent back to the web service.
Issue: overleaf/issues#1286
This will also make output files and logs available when you manually stop a compile.

Send output files on timeout

---

app/coffee/OutputCacheManager.coffee

This fixes a tiny regexp bug that prevents output files in subfolders
from being shown in the "Other logs & files" panel.
We also downgrade the corresponding log because it's very noisy and does
not indicate a problem.
I stumbled upon that while looking at noisy logs (https://github.com/overleaf/issues/issues/2470)
This looks like a bug, but maybe it was intentional. I'd like to have other opinions on the matter.
This will increase the number of output files returned by CLSI, which could increase the storage demands on the CLSI output cache. It will also exacerbate an existing problem in the UI with long output file names.

Show output files in subfolders

---

Dockerfile

Upgrade to a locally built node 10.18.1 base image. This is in preparation for another upgrade later.
overleaf/issues#2705
This upgrades node from 10.15.0 to 10.18.1. We should try it out in staging first, then monitor a bit when it goes to prod.
The ops team

Upgrade to local node:10.18.1 image

---

Dockerfile
Jenkinsfile
Makefile
buildscript.txt
docker-compose-config.yml
docker-compose.ci.yml
docker-compose.yml

Update the build scripts for https://github.com/overleaf/dev-environment/pull/294
This adds a new `base` stage for the docker image.
https://github.com/overleaf/dev-environment/pull/294
- `language=es`
The eslint rules changed in the build-scripts, which required some formatting
changes. These were automatically applied by `prettier-eslint --write`.
- `spelling`
An additional tweak was required to cleanup a pending task for the unit-tests.
- `filestore`,  `spelling` and `third-party-datastore`
See https://github.com/overleaf/dev-environment/pull/294#issuecomment-584777526
for details on the added `data-dir` parameter.
Low.
We will notice any complications in regards to starting the services in staging.

[misc] update the build scripts to 1.3.5

---

entrypoint.sh

was removed as part of https://github.com/overleaf/clsi/pull/152, copying synctex still required, should be tested in stag

copy synctex over to /app/bin/synctex-mount in entrypoint

---

Makefile
buildscript.txt

This will put acceptance and unit tests in own namespaces so that they
can run and be teared down individually.
https://github.com/overleaf/dev-environment/pull/330

[misc] bump the build-scripts to version 2.1.0

---

app/js/ResourceWriter.js
test/unit/js/ResourceWriterTests.js

This could have helped us in detecting todays failure on a per node basis.
Also we are able to set an alert trigger for the future.
Low.
- unit and acceptance tests pass locally
`download_failed`

[misc] add a metric for failing downloads

---

app/js/DockerRunner.js
test/unit/js/DockerRunnerTests.js

The error message scheme for dockerode/docker-modem errors has changed
back in 2016: https://github.com/apocas/docker-modem/commit/f47544d20f76e59b3ade708744ed3f920a63119b
```diff
- HTTP code is 500 which indicates error: server error
+ (HTTP code 500) server error - OCI runtime create failed: ...
```
As a result we no longer retry compiles on internal docker errors.
Snip from the currently used version: https://github.com/apocas/docker-modem/blob/v2.1.1/lib/modem.js#L296
> `        '(HTTP code ' + res.statusCode + ') ' +`
Low.

[misc] keep up with the error signature of dockerode/docker-modem

---

.dockerignore
Dockerfile
buildscript.txt
config/settings.defaults.js
db/.gitignore
entrypoint.sh
test/acceptance/js/ExampleDocumentTests.js

Use the new `data-dirs` approach in the build-scripts for marking directories as writable for the run-time user.
The run user will be able to write here:
- /app/cache
- /app/compiles
- /app/db
- for tests in some test/acceptance directory -- there is no need to flag this as a volume.
Changing the ownership is a massive performance hit for the startup.
With that removed, expect that boxes come up much faster.
Prettier was complaining about the line length in the settings defaults.
~There is a race condition in CI, cloud-builder would run `test_clean` -- a prerequisite from `test_acceptance` -- and try to clean the `test_unit` container. The commit https://github.com/overleaf/clsi/commit/f30f4ab96ebcecfdbe2f2f0f725deb08145ce0d5 fixes that in putting the two invocations into two namespaces …

[misc] entry point cleanup

---

app.js
app/js/ProjectPersistenceManager.js
package-lock.json
package.json
test/unit/js/ProjectPersistenceManagerTests.js

on clsi all data lives inside of / dir
dynamically reduce size of EXPIRY_TIMEOUT if disk starts to get full
adds refreshExpiryTimeout which modifies EXPIRY_TIMEOUT if the disk is filling up
doesn't drop EXPIRY_TIMEOUT to below 50% of the normal threshold to prevent any runaway bugs

add refreshExpiryTimeout function

---

app/js/UrlCache.js
app/js/UrlFetcher.js
test/acceptance/js/UrlCachingTests.js
test/unit/js/UrlCacheTests.js
test/unit/js/UrlFetcherTests.js

Adds pipeUrlToFileWithRetry function to retry file downloads up to 3 times. Replaces logic which was used in the filestore to retry failed downloads from gcs/s3
https://github.com/overleaf/issues/issues/2962
Medium, worth checking the number of requests to GCS doesn't increase once this is live

add pipeUrlToFileWithRetry for file downloads

---

app/js/CompileManager.js
app/js/LocalCommandRunner.js
app/js/OutputFileFinder.js
app/js/OutputFileOptimiser.js
test/unit/js/CompileManagerTests.js
test/unit/js/OutputFileFinderTests.js

Reading process output in a `data` event using .toString() works most of the time but can lead to utf8 characters being broken across chunk boundaries.  The correct way is to set the encoding on the stream.
https://nodejs.org/api/stream.html#stream_readable_setencoding_encoding
NA
Similar case fixed in spelling https://github.com/overleaf/spelling/pull/36
Small change.
Output file list in production
NA
NA
NA

set encoding when reading from streams

---

app/js/OutputFileOptimiser.js
app/js/SafeReader.js
test/unit/js/OutputFileOptimiserTests.js

This replaces usage of the Buffer constructor `new Buffer` with  `Buffer.alloc` and `Buffer.from`.  The buffer constructor has been deprecated for a long time, as it leaves memory uninitialised.
> `(node:49) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`
https://nodejs.org/api/buffer.html
NA
Small change
Low
NA
NA
NA
NA
NA

fix deprecated usage of Buffer constructor

---

app.js
package-lock.json
package.json
test/smoke/js/SmokeTests.js

For https://github.com/overleaf/issues/issues/2782#issuecomment-625269923
This PR removes the dependency on the out-dated `smoke-test-sharelatex` package and replaces the test running via mocha with simple requests and non-raising assertions.
_Basically a port of https://github.com/das7pad/clsi-sharelatex/commit/fe83b4451da0b4408208b9337e088ef3d24c304e_ 
https://github.com/overleaf/issues/issues/2782#issuecomment-625269923
I preserved the logic of not caching test results from `/smoke_test_force` runs, but I am happy to change that (and simplify `test/smoke/js/SmokeTests.js` even further).
As part of the `resCacher`  refactoring I changed the process shutdown to a `setTimeout` handler which manipulates a variable in the parent scope -- there is no need to check for the process age on …

[misc] simplify the smoke test and process shutdown

---

app/js/DockerRunner.js
test/unit/js/DockerRunnerTests.js

As part of the investigation for https://github.com/overleaf/issues/issues/2913 we have seen [this error](https://console.cloud.google.com/logs/viewer?project=mgcp-1117973-ol-prod&minLogLevel=0&expandAll=false&timestamp=2020-04-06T13%3A00%3A00.000000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2020-04-06T12%3A00%3A00.000Z&dateRangeEnd=2020-04-06T14%3A00%3A00.000Z&interval=JUMP_TO_TIME&resource=k8s_container%2Fcluster_name%2Fol-gke-02%2Fnamespace_name%2Fdefault&scrollTimestamp=2020-04-06T13%3A15%3A48.826999902Z&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%228160762138875827907%22%0Aresource.labels.zone%3D%22us-east1-b%22%0Aresource.labels.project_id%3D%22mgcp-1117973-ol-prod%22%0Atimestamp%3D%222020-04-06T13%3A15%3A48.826999902Z%22%0Ainse …

[DockerRunner] retry container inspect on EPIPE

---

app/js/DockerRunner.js
test/unit/js/DockerRunnerTests.js

The docker api returns each name with a `/` prefix.
In order to not interfere with pending compiles, the deletion process
has to acquire an internal lock on the container. The LockManager uses
the plain container name without the slash: `project-xxx` [1].
<details>
<summary> error log message caused by the missing lock </summary>
https://github.com/overleaf/clsi/blob/f285e08ee055e7b0fc0c81d598a61f40cfdebeb4/app/coffee/DockerRunner.coffee#L315
```json
{
"container_id": "fe66435f9...",
"err": {
"json": {
"message": "You cannot remove a running container fe66435f9.... Stop the container before attempting removal or force remove"
},
"message": "(HTTP code 409) unexpected - You cannot r...",
"name": "Error",
"stack": "...",
"statusCode": 409
},
"msg": "error destroying container"
}
``` …

[DockerRunner] destroyOldContainers: normalize the container name

---

app/js/CompileManager.js
app/js/LatexRunner.js
app/js/ResourceWriter.js
test/unit/js/LatexRunnerTests.js
test/unit/js/ResourceWriterTests.js

Currently it is not possible to see the `latexmk` output for a compile, only the tex log file.  This PR writes the latexmk output into two files `output.stdout` and `output.stderr` which can be downloaded from the "Other logs & files" dropdown.  This information should be helpful for debugging support issues.  
https://github.com/overleaf/issues/issues/3048
For simplicity I have written the files in the background... maybe a bit lazy?  I can clean it up if needed.
Low
NA
NA
NA
NA
@emcsween @henryoswald

record latexmk output

---

app/js/DockerRunner.js
config/settings.defaults.js
test/unit/js/DockerRunnerTests.js

Import of https://github.com/overleaf/clsi/pull/141 (CI won't run there...)
> The docker api returns each name with a `/` prefix.
>
> In order to not interfere with pending compiles, the deletion process
has to acquire an internal lock on the container. The LockManager uses
the plain container name without the slash: `project-xxx` [1].
Due to the missing locking, there is a race between cleanup and active
compiles.
For https://github.com/overleaf/issues/issues/3093
Low, affects container cleanup only

[DockerRunner] destroyOldContainers: fix a race confition

---

app/js/CompileManager.js
config/settings.defaults.js

Allow setting `openout_any` when running compiles.
NA
https://github.com/overleaf/issues/issues/3048
I've added this as a setting to avoid the work of updating all the texlive images.  It's also easier to revert if we encounter problems.  If it works out ok we can move it into the images and delete this code.
Low.
NA
NA
NA
NA

add setting TEXLIVE_OPENOUT_ANY

---

config/settings.defaults.js

Exit on startup if the seccomp profile cannot be loaded.
NA
NA
The code path to load the seccomp profile is only followed for DockerRunner instances. We always attempt to load it in that case.
Low.
NA
NA
NA
NA
cc @mserranom if this affects server pro

error on missing profile

---

config/settings.defaults.js

This PR adds a missing setting for `clsi.optimiseInDocker` at [OutputCacheManager.js#L355-L364](https://github.com/overleaf/clsi/blob/cffbd4e9efbdab23534f9c3e96ea7a808417fa5d/app/js/OutputCacheManager.js#L355-L364), which skips any attempt to optimise the final pdf when qpdf is running in the docker container.  There is no qpdf outside the container so that always fails. 
NA
NA
Small change.
Optimisation of pdf only.
NA
NA
NA
cc @mserranom

add missing setting for optimiseInDocker

---

app/js/DockerRunner.js
test/unit/js/DockerRunnerTests.js

Partially revert [[DockerRunner] fix metric incrementing and error logging](https://github.com/overleaf/clsi/pull/162)
This reverts commits:
- 2b2fcca39ce8dee0fdc0c342aa0d6c822592bcec
- 9e82ab0890c5cc8c7fb95362c3f7edbcaad0cf29
- e3da458b376871c3ce72d6984d14bf1ee668b04b
As discussed in https://github.com/overleaf/issues/issues/2913

Remove Retries in EPIPE Errors

---

app/js/DockerRunner.js
app/js/OutputCacheManager.js
app/js/OutputFileOptimiser.js
app/js/db.js
package-lock.json
package.json
test/load/js/loadTest.js
test/unit/js/DockerRunnerTests.js
test/unit/js/OutputFileOptimiserTests.js

Migrate from `underscore` to `lodash`.  I needed to use a `lodash` function in another PR so it was time to migrate.
NA
NA
We only use a few `underscore` functions, and they are available in `lodash` without any change to the signature.
I had to update the sandbox module calls in the unit tests to include `Math` as a `global` because `lodash` makes use of it and causes the tests to fail if it is unavailable.
Low
NA
NA
NA
NA

migrate from underscore to lodash

---

app.js
app/js/CompileManager.js
test/acceptance/js/SynctexTests.js
test/acceptance/js/helpers/Client.js

This PR reinstates the check that the synctex output file exists before running synctex.  The code was still there but somehow the call to the check was lost in previous refactoring.
We see a lot of 500 errors in the logs for requests like "/project/123456789abcdef/user/123456789abcdef/sync/code?file=article.tex&line=731&column=0".  These increase after a deploy due to synctex failing when the output file does not exist.
NA
https://github.com/overleaf/clsi/pull/175
I have added back the check and cleaned it up so it is only called in one place (in `_runSynctex`).  It now returns a 404 when the project directory or syntex file do not exist.
I've also degraded the NotFound error to a log entry rather than a warning - it is only used by the synctex file checking.
Low, affects synctex errors …

fix synctex error

---

app/js/CompileManager.js
app/js/DockerRunner.js
app/js/LatexRunner.js
app/js/LocalCommandRunner.js
app/js/RequestParser.js
config/settings.defaults.js
test/unit/js/CompileManagerTests.js
test/unit/js/DockerRunnerTests.js
test/unit/js/LatexRunnerTests.js

This PR adds support for overriding individual docker container settings based on an extra "compile group" parameter.  For example, a "priority" compileGroup could override the HostConfig.CpuShares configuration to give containers in that group more cpu than other groups.  Any other setting for the docker container can also be overridden.  The optional `compileGroup` parameter is sent in the clsi request from web. 
NA
https://github.com/overleaf/issues/issues/2458
To allow individual settings to be overridden, the configuration uses dotted path based keys with lodash's `_.set(obj,path,val)` method (otherwise entire subobjects would be overwritten, rather than individual properties).  This requires a migration from underscore to lodash, which is in #178. 
Web already has a concept of …

add compile groups support

---

app/js/CompileController.js

Adds missing handling of EPIPE errors in the CompileController
After watch a few deploys I realised that the check for the EPIPE errors in the error handling middleware was missing a lot of errors - it turns out the CompileController does its own handling of the response code, so we need to check there too.
Previous attempt https://github.com/overleaf/clsi/pull/175
Small change
Should only affect instances that are shutting down.
NA
NA
NA
Look at 500's chart for the clsi.
@henryoswald

handle EPIPE errors in CompileController

---

test/acceptance/js/ExampleDocumentTests.js

We are already detecting the failure of the compilation, let's raise it immediately after logging.
There is no need to move on and fail with a random access error:
`Client.getOutputFile` will likely return `pdf = null` and `pdf.url` will error out.
<details>
<summary>Error before applying the patch</summary>
<pre>
13) Example Documents
knitr
should generate the correct pdf:
Uncaught TypeError: Cannot read property 'url' of null
at Request._callback (test/acceptance/js/ExampleDocumentTests.js:214:79)
at Request.self.callback (node_modules/request/request.js:185:22)
at Request.<anonymous> (node_modules/request/request.js:1161:10)
at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
at endReadableNT (_stream_readable.js:1094:12)
at process._tickCallback …

[ExampleDocumentTests] drop out in case of an error during compilation

---

app/js/LocalCommandRunner.js

_Given that you are still supporting the local runner (#131), this might be of interest too._
The subprocess event handler fires the "error" and "close" event in case
of a failure.
Both events would call the given callback, resulting in double
processing of the subprocess result downstream.

[LocalCommandRunner] run: block a double call of the callback

---

app/js/CompileController.js
app/js/DockerRunner.js
app/js/RequestParser.js
config/settings.defaults.js
docker-compose-config.yml
test/acceptance/js/AllowedImageNames.js
test/acceptance/js/helpers/Client.js
test/unit/js/CompileControllerTests.js
test/unit/js/DockerRunnerTests.js
test/unit/js/RequestParserTests.js

For https://github.com/overleaf/issues/issues/3171
We may want to downgrade the server error (500) to a client error (400) when a compile request fails the validation. This should be done in a different PR as it likely involved changes in web.
https://github.com/overleaf/issues/issues/3171
https://github.com/overleaf/google-ops/pull/1113 to inject the environment variable (optional, this PR can get deploy independently).
High. Users with bad entries in the db might have to reset the imageName from the ui.
- added unit and acceptance tests

[misc] RequestParser: restrict imageName to an allow list and add tests

---

app/js/CompileManager.js

`Settings.clsi` has been `undefined` on Overleaf CE until `Settings.clsi.optimiseInDocker` was introduced in https://github.com/overleaf/overleaf/pull/740.
This was causing a null pointer exception in `CompileManager` when invoking `synctex`:
```
/var/www/sharelatex/clsi/app/js/CompileManager.js:539
Settings.clsi != null ? Settings.clsi.docker.image : undefined,
^
TypeError: Cannot read property 'image' of undefined
at Object._runSynctex (/var/www/sharelatex/clsi/app/js/CompileManager.js:539:52)
at /var/www/sharelatex/clsi/app/js/CompileManager.js:437:29
at xfs.stat (/var/www/sharelatex/clsi/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
at callback (/var/www/sharelatex/clsi/node_modules/graceful-fs/polyfills.js:295:20)
at FSReqWrap.oncomplete (fs.js:154:5)
```
Fixes …

Fixed NPE when Settings.clsi is defined but Settings.clsi.docker is not

---

app/js/DockerRunner.js
test/unit/js/DockerRunnerTests.js

When we mount the container's root filesystem as read-only, mount an anonymous volume in /home/tex so that it's writable. Our TeX Live images have cached content in /home/tex. This content will automatically get copied by Docker into this 
anonymous volume.
* overleaf/texlive-images#28
I initially thought I'd need to change more code, so I did a decaf cleanup. As usual, it's in separate commits and best reviewed commit by commit.
The changes only impact read-only mode, which is not turned on in production at the moment.

Mount /home/tex in an anonymous volume

---

app.js
app/js/Metrics.js
package-lock.json
package.json

For https://github.com/overleaf/issues/issues/3502
- renamed package from `metrics-sharelatex` to `@overleaf/metrics`
- drop support for statsd backend
- decaffeinate
- compress `/metrics` response using gzip
- bump debugging agents to latest versions
- expose prometheus interfaces for custom metrics (custom tags)
- cleanup of open sockets metrics
- fix deprecation warnings for header access
For https://github.com/overleaf/issues/issues/3502
High. Incomplete metrics collection.
- create a new project
- open a project in the editor
- make changes to a document, reload the editor to check persistence
- compile a project
- open the history tab in the editor
- all services seem to be running fine in the dev-env
- check for compression on the `/metrics` endpoint:
- `$ curl …

[misc] bump metrics module to 3.4.1

---

package-lock.json
package.json

For https://github.com/overleaf/issues/issues/3731
Installing npm packages via git is flaky (https://github.com/overleaf/third-party-references/pull/42).
This PR is switching the installation of the setttings module to the existing npm package -- which all the other service are using too.
For https://github.com/overleaf/issues/issues/3731
Low. The tests are not working without this package being properly installed, so the chance of it breaking in prod are low.

[misc] install settings-sharelatex from npm

---

app/js/CompileController.js
test/unit/js/CompileControllerTests.js

For cleanup under the umbrella of https://github.com/overleaf/issues/issues/3777
The previous regex could mistake user provided pdf files, like
`fake_output.pdf`, as the final output file.
The frontend expects to find a `output.pdf` file on success.
https://github.com/overleaf/web-internal/blob/5553ede59d75306a7085424b5e0a20dabe0792f5/frontend/js/ide/pdf/controllers/PdfController.js#L372-L395
https://github.com/overleaf/issues/issues/3777
This code base is due for a big decaff-cleanup, hence I restrained from simplying the loop and made a minimal change.
Low.
- added test case

[misc] CompileController: exact match for output.pdf

---

app/js/ResourceStateManager.js

Decaff cleanup of ResourceStateManager.
NA
NA
I also changed an occurrence of {} to a Set for safety.
ResourceStateManager controls the check for incremental vs full compiles.  
NA
NA
Metrics are here: https://github.com/overleaf/web-internal/blob/0ee54ec4721e96fce84d0f5c950353ce5c166010/app%2Fsrc%2FFeatures%2FCompile%2FClsiManager.js#L514-L524
We need to add the metrics for full vs incremental compiles to a dashboard to see them in stackdriver.  Can look at them in prometheus for a quick check.

decaff cleanup ResourceStateManager

---

.gitignore
Dockerfile
app.js
app/js/CompileManager.js
app/js/OutputCacheManager.js
config/settings.defaults.js
test/unit/js/CompileManagerTests.js

This PR copies the generated output files from a compile into a separate output directory so they can be served by a different process.  
In future this will allow the compile directory to cleared (the "clear cache" option in the front end) while keeping the output files, but at the moment both directories are cleared when the cache is cleared.
NA
https://github.com/overleaf/google-ops/pull/1444
https://github.com/overleaf/issues/issues/3207
I have added a `logger.warn` line when files are served using the old method.
Affects PDF output
NA
Can be deployed gradually,  there is no change to the REST API.
NA
@mans0954 @das7pad

use separate output dir for generated files

---

app.js
config/settings.defaults.js

Add an uncaughtException handler to the clsi,  enabled when the environment variable `CATCH_ERRORS` is set to "true".
NA
#204
The code is copied from web [app.js#L33-L38](https://github.com/overleaf/web-internal/blob/460ac7cdcb36ac18631bb021d04f3ce9924737ec/app.js#L33-L38).
Low.  May cause exceptions to go unnoticed.
Expected output:
```
clsi_1                    | {"name":"clsi","hostname":"1bdc9193edae","pid":46,"level":50,"err":{"message":"Test error","name":"Error","stack":"Error: Test error\n    at Timeout._onTimeout (/app/app.js:218:11)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)","info":{}},"msg":"uncaughtException","time":"2021-01-26T15:26:27.342Z","v":0}
```
NA …

add uncaughtException handler

---

test/unit/js/ResourceStateManagerTests.js

This adds a unit test for the case of a missing state file (in addition to the tests for matched and unmatched state files)
In #200 I removed a guard function that I thought wasn't needed -- it turned out that it was needed, but there was no unit test for that case.
N/A
#200 and #208
Adds unit test only
There will be another PR to add in the broken code in #200 and add a fix which will make the test pass.
NA
NA
NA
NA 
NA
cc @henryoswald

add unit test for non-existent state file

---

app/js/ResourceStateManager.js

This adds a fix for the exception in the decaff cleanup of ResourceStateManager.
The fix is in the commit https://github.com/overleaf/clsi/commit/f84ba5ad4cbdee1658911a7b82f45b21181141f9
The other two commits bring back the original decaff cleanup commit (by reverting the revert commit) and bring in the additional unit test for the exception in #206.
NA
#200 and #206
overleaf/issues#3207
I added a test on `result` and fall back to an empty array `[]` when undefined (the original behaviour).
Code path is hit when user clears cache.
NA
NA
Check logs for any uncaught exception errors from #207 
NA

fix for exception in "decaff cleanup ResourceStateManager"

---

README.md

Requested change to https://github.com/overleaf/clsi/pull/213
I couldn't find a link to authoritative documentation as to what the `openout_any` env variable actually does. CC @GrahamMDouglas

Add missing environment variables to CLSI README.

---

entrypoint.sh

This runs `mkdir -p` to ensure that each folder is created before running `chown node:node`, in `entrypoint.sh`, to avoid an error that's otherwise thrown when the `app/cache` folder doesn't exist on the host: 
```
/bin/chown: cannot access '/app/cache': No such file or directory
```
There's something similar in `Dockerfile` but it only runs in the `app` stage:
```Dockerfile
RUN mkdir -p cache compiles db output \
&&  chown node:node cache compiles db output
```

Ensure that app folders exist before running chown in entrypoint.sh

---

app/js/OutputFileOptimiser.js

This fixes an issue where CE/SP users (not using sandboxed compiles), and using the optimization pass built into CLSI (rather than in a texlive docker image), would end up with optimized PDFs that failed PDF/A validation.
This PR adds the `--newline-before-endstream` flag when invoking `qpdf`, preserving PDF/A compliance.
This code path is used when all of these conditions are met:
- running in CE, or in Server Pro
- without sandboxed compiles
- `OPTIMISE_PDF` is set to `false`
**NOTE!!!**: `OPTIMISE_PDF` is misleadingly named, as it corresponds to `Settings.clsi.optimiseInDocker` in the settings file. By default this is set to `true` in CE/SP, meaning that the application should _rely on the texlive docker process to optimise the PDF_. Setting this to `false` does not mean "Don't …

Add flag to qpdf, to preserve PDF/A compliance

---

app/js/CompileController.js
app/js/CompileManager.js
test/acceptance/js/AllowedImageNames.js
test/acceptance/js/SynctexTests.js
test/acceptance/js/helpers/Client.js
test/unit/js/CompileControllerTests.js
test/unit/js/CompileManagerTests.js

For https://github.com/overleaf/issues/issues/3170
papercut 27
^ a bit more than a papercut.
This PR is adding request parsing/validation and passing around of a custom imageName for synctex requests.
For https://github.com/overleaf/issues/issues/3170
papercut 27
The handling is very similar to the `image` parameter handling in the wordcount handling. I've aligned the query flag for the two synctex endpoints with the internal label in mongo and in the compile request body. 
The PR is best reviewed with whitespace changes ignored due to a few indentation changes from adding parameter to functions.
Low. It handles a missing flag just fine.
- see added tests
- setup dev-env like prod https://github.com/overleaf/dev-environment/pull/466
- set image name to the evil image
- try …

[misc] consume and validate a custom imageName for synctex requests

---

app/js/CompileController.js
app/js/CompileManager.js
app/js/ContentCacheManager.js
app/js/ContentCacheMetrics.js
app/js/OutputCacheManager.js
config/settings.defaults.js
docker-compose.ci.yml
docker-compose.yml
test/acceptance/js/Stats.js
test/acceptance/js/helpers/Client.js
test/unit/js/CompileControllerTests.js
test/unit/js/CompileManagerTests.js

I've split all the changes into logic commits:
- exercise the pdf caching logic in CI
- expose `stats` and `timings` all the way to the frontend ( https://github.com/overleaf/web-internal/commit/1a601c1816214bb47a49bcb1334be378417c2c92 )
- logging of error from saving output files (and hashing contents)
- the new metrics as discussed in our call
- a _dark mode_ for doing the hashing of ranges only and emitting an empty file to disk, no ranges will be passed to the frontend `ENABLE_PDF_CACHING_DARK="true"`
<details>
<summary> dark mode </summary>
```
$ ll clsi/output/5fd2393db7aab600269c7212-5efc543e0c774e0026c8598b/content/1795bfd00ba-80b48763bcb31ac9/
total 69884
drwxr-xr-x 2 me me    4096 May 11 16:12 ./
drwxr-xr-x 3 me me    4096 May 11 16:12 ../
-rw-r--r-- 1 me me 2628690 May 11 16:12 …
```

[misc] add metrics for pdf caching and dark mode for compute only

---

app/js/ContentCacheManager.js
config/settings.defaults.js

This PR is adding a config options for the min chunk size of pdf ranges. We will need to bump the chunk size for a production environment.
Low.

[misc] add a config option for the min chunk size of pdf ranges

---

test/bench/hashbench.js

Adds a benchmark script for the content hashing
NA
I notice we are using the default value of 64k for the highWatermark on fs.createReadStream.  Increasing it to 1MB helps, there's no benefit beyond that though.
With default highWatermark on fs.createReadStream
```
root@clsi-reg-e2-a-d4sz-ctr:/app# time node test/bench/hashbench.js /app/compiles/AMS55.pdf 
/app/compiles/AMS55.pdf hashType md5 cold-start 1755.19 ms warm-start 651.24 ms
/app/compiles/AMS55.pdf hashType sha1 cold-start 1324.65 ms warm-start 443.96 ms
/app/compiles/AMS55.pdf hashType hmac-sha1 cold-start 1394.18 ms warm-start 537.54 ms
/app/compiles/AMS55.pdf hashType sha256 cold-start 1305.88 ms warm-start 420.96 ms
DONE
real	0m8.477s
user	0m6.000s
sys	0m4.436s
```
With highWatermark:1024*1024 on fs.createReadStream the …

add hash benchmark script

---

app/js/UrlCache.js
test/unit/js/UrlCacheTests.js

The `fs-extra` module has a `copy` method which uses the native fs.copyFile method for performance. It's a useful module.
NA
NA
Performance improvement.
Compiles
NA
NA
NA
NA
@henryoswald

use fs.copyFile for performance

---

app/js/ResourceWriter.js

This PR is dropping a useless synchronous syscall on the hot path for writing docs to disk as part of a compile request.
No ticket, I noticed this while starting to port the service to Golang.
https://github.com/overleaf/clsi/pull/86 ( 3 years ago :see_no_evil: )
Low.
- run unit/acceptance tests locally

[perf] drop useless synchronous syscall on hot path for writing docs

---

app/js/ContentCacheManager.js
test/unit/js/ContentCacheManagerTests.js

For https://github.com/overleaf/clsi/pull/224#issuecomment-839883764
This PR is adding support for stream detection across chunks. 
For https://github.com/overleaf/clsi/pull/224#issuecomment-839883764
Retain a small part (6 or 9 bytes) of each chunk in memory for providing
the next iteration with enough context for finding the start/end marker
of a range.
I've also added constants for the markers.
Low.
```
stream = [
Buffer.from("abcstr"),
Buffer.from("eam123endstreamABC"),
Buffer.from("str"),
Buffer.from("eam(|"),
Buffer.from(")end"),
Buffer.from("stream-_~stream!$%endstream"),
]
```

[ContentCacheManager] add support for stream detection across chunks

---

app/js/ContentCacheManager.js

For https://github.com/overleaf/clsi/pull/235#issuecomment-842412183
This PR is adding a tracker for written hashes and skips writing for already written hashes. 
For https://github.com/overleaf/clsi/pull/235#issuecomment-842412183
Low.
- Re-upload an image under a new name
- Add verbose logging, see diff below
- Compile with pdf caching
- See skipped duplicate
```
...
clsi_1                    | writing hash 8bcdc00b46e2821baa405bf18fb73e5b9fb743ae7f1d55c7dc9330c968ea2a52
clsi_1                    | writing hash 77debd1c216f91849fa11961ee13389405237d067b98e3b476f8a6864a36e5db
clsi_1                    | writing hash 7fb799a681f290cf0c943f2e95700702fb0c2f9680135a192e2b7b8690b16e90
clsi_1 …
```

[ContentCacheManager] skip writing of duplicate streams

---

test/acceptance/js/AllowedImageNamesTests.js

Apparently I forgot to add `done` callbacks to the imageName tests and nobody noticed :shrug: 
_(...until they broke while I was porting the service to Golang :smile: )_
#183 
I check the other test suites and they are looking good.
Low. CI only changes.
- run acceptance tests locally

[misc] AllowedImageNamesTests: add missing done callbacks

---

app.js
app/js/ProjectPersistenceManager.js
test/unit/js/ProjectPersistenceManagerTests.js

For https://github.com/overleaf/issues/issues/4121
We are going to add more disks to the VMs and mount them to a non root path. This PR is extending the disk-full check to look at all the user content directories: compiles, output and file cache.
For https://github.com/overleaf/issues/issues/4121
I included a bonus patch, adding a delay to the cleanup process to allow the disk-full check to complete first.
Medium, disk filling up is bad.
- adjusted unit tests

[ProjectPersistenceManager] check all user content dirs for full disk

---

.eslintrc
app/js/LocalCommandRunner.js
buildscript.txt

For https://github.com/overleaf/issues/issues/3851
Uses https://github.com/overleaf/dev-environment/pull/470
> This PR is adding linting rules for flagging imports from npm that are not properly specified in the package.json. Either they are missing at all and the `node_modules/` entry is there by chance via another dependency, or they are specified in the wrong section, e.g. using a `devDependency` in `app/js/`.
For https://github.com/overleaf/issues/issues/3851
Uses https://github.com/overleaf/dev-environment/pull/470
Low.

[misc] add linting for missing explicit dependencies and fix any errors

---

app/js/CompileController.js
test/unit/js/CompileControllerTests.js

For https://digital-science.slack.com/archives/C20TZCMMF/p1624355499030500
This PR is flagging broken compiles with an empty output.pdf as a compile failure. This should help in cutting down the noise in sentry (and provide a better UX).
For https://digital-science.slack.com/archives/C20TZCMMF/p1624355499030500
Some output file fields are optional and they have been copied conditionally from the _internal_ file to the output file object. This complicates writing tests for as `JSON.stringify` is not as strict as `sinon.stub().calledWith` and hence requires special handling for _missing_ field when writing tests (the former drops undefined, the later requires exact matches). To simplify all of this I am now destructing the _internal_ file attributes into the output file entry. This has been …

[CompileController] emit status=failure for an empty output.pdf file

---

app/js/ContentCacheMetrics.js

For https://digital-science.slack.com/archives/C0216GDEG9L/p1624437084020500
This PR is logging seemingly slow pdf caching performance. It may as well be very fast compiles that show a high overhead.
With lowered threshold:
```
clsi_1                    | {"name":"clsi","hostname":"ca2ae0f26e11","pid":46,"level":40,"stats":{"latexmk-errors":0,"latex-runs":1,"latex-runs-with-errors":0,"latex-runs-1":1,"latex-runs-with-errors-1":0,"pdf-size":61957,"pdf-caching-n-ranges":6,"pdf-caching-total-ranges-size":59595,"pdf-caching-n-new-ranges":0,"pdf-caching-new-ranges-size":0,"pdf-caching-reclaimed-space":0},"timings":{"compute-pdf-caching":12,"compile":591,"compileE2E":645},"load":[1.2,1.02,1.02],"msg":"slow pdf …
```

[misc] ContentCacheMetrics: log slow pdf caching performance

---

app/js/CompileManager.js
app/js/ContentCacheManager.js
app/js/ContentCacheMetrics.js
app/js/Errors.js
app/js/OutputCacheManager.js
app/lib/pdfjs/FSPdfManager.js
app/lib/pdfjs/FSStream.js
app/lib/pdfjs/parseXrefTable.js
config/settings.defaults.js
test/unit/lib/pdfjsTests.js

This PR is adding processing deadline to the pdf caching logic. The deadline is 10s or 1/4 of the compile time, what ever is lower. This will allow slow compiles (120s) to use 10s of overhead and a 12s compile at most 3s. We can tweak this later.
lower deadline from 10s to 1ms
```
clsi_1                    | {"name":"clsi","hostname":"4bfb59052377","pid":277,"level":40,"err":{"message":"after init HashFileTracker","name":"TimedOutError","stack":"TimedOutError: after init HashFileTracker\n    at /app/app/js/ContentCacheManager.js:249:13\n    at Object.update (/app/app/js/ContentCacheManager.js:30:3)","info":{"lastStage":"start","diffToLastStage":2}},"outputDir":"/app/output/60b0dd39c418bc00598a0d22-5efc543e0c774e0026c8598b","stats":{"latexm …
```

[misc] bail out from pdf caching processing after 10s or earlier

---

app.js

I decided to try and keep load shedding as simple as possible for the first attempt. This is the simplest possible implementation I think we can do and should prove a useful test. We can initially deploy it to 1 instance group and watch how it behaves over a few days. 
The change made is when the box is over 100% capacity start to shed load.
If this proves successful we can then roll it out to more instance groups and possibly make shedding more aggressive (targeting ~90% cpu usage etc)
https://github.com/overleaf/issues/issues/4137
- Medium, projects could stampeded all over our clsi's if we shed too much
https://console.cloud.google.com/monitoring/dashboards/builder/6376263191972157537?authuser=1&project=mgcp-1117973-ol-prod&dashboardBuilderState=%257B%2522editModeEnabled%2522:false%257D …

very basic mvp for shedding load

---

app/js/CompileManager.js

For https://github.com/overleaf/issues/issues/4151
This PR is adding two timings for the project file syncing stage and output file copying/processing stage. The clsi-perf service will consume these timings.
For https://github.com/overleaf/issues/issues/4151
Low.
- compile in dev-env

[misc] add timings for the sync stage and output stage

---

app/js/UrlFetcher.js
config/settings.defaults.js
test/unit/js/UrlFetcherTests.js

For https://github.com/overleaf/issues/issues/4151
Checking logs reveled that we forgot to handle the filestore override for clsi-perf downloads. This PR is adding an explicit exception for clsi-perf. 
For https://github.com/overleaf/issues/issues/4151
Low, unit/acceptance tests cover this code path.
- add unit test
- clear compile/cache/db dirs and compile a project with images in dev-env

[UrlFetcher] do not override domain for clsi-perf requests

---

install_deps.sh

This PR is speeding up the builds slightly (~6:30-7:30 -> ~5:30-6:00).
- install docker cli only
- drop vim install
https://console.cloud.google.com/cloud-build/builds?project=overleaf-ops&pageState=(%22builds%22:(%22f%22:%22%255B%257B_22k_22_3A_22Tags_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22clsi_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22tags_22%257D%255D%22))
Docker install steps were taken from https://docs.docker.com/engine/install/debian/
Bonus: I've added `set -e` for bailing out and deleted the apt-package lists.
Low. We do not invoke docker inside the clsi container in prod for anything important (only a `docker --version` check).
- CI passes

[perf] trim down install_deps.sh -- install docker cli only
